<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Axia_Analyse.Service.Interfaces</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CryptoHelper" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Axia-Analyse.Data.Interface\Axia-Analyse.Data.Interface.csproj" />

  </ItemGroup>

</Project>
